apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argo-cd  # This should be the namespace where ArgoCD is installed
spec:
  project: default
  source:
    repoURL: https://github.com/pavlosmcg/argocd-example-apps  # Replace with your fork
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
